# Generated by Django 2.2.2 on 2022-05-23 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='up/')),
                ('phon_number', models.CharField(max_length=11)),
                ('card_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('money', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='upload/')),
                ('price', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Category')),
                ('desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Movie_desc')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Video')),
            ],
        ),
    ]
